
import java.util.ArrayList;
import javax.swing.JOptionPane;

//import java.util.ListIterator;
import javax.swing.DefaultListModel;

public class Taylor extends javax.swing.JFrame {
ArrayList<Product> stuff=new ArrayList();
DefaultListModel list = new DefaultListModel();
Product p;
static int index;
static int numprod;
static int price;
    public Taylor() {
        initComponents();
     price=200;
     p=new Dress("");
     stuff.add(p);
     list.addElement(p.getName());
     txtnumber.setText(""+numprod);
     txtindex.setText(""+index);
     
      
    }
   public static int findInsertPoint(ArrayList a, Object searchValue) {
        int left = 0;
        int right = a.size() - 1;
        int midp = 0;

        while (left <= right) {
            midp = (left + right) / 2;
            int result = ((Comparable) a.get(midp)).compareTo(searchValue);

            if (result < 0) {
                left = midp + 1;
            } else {
                right = midp - 1;
            }
        }
       if (((Comparable) a.get(midp)).compareTo(searchValue) < 0) {
          midp++;
       }
        return midp;
    }
     public static int search(ArrayList a, Object searchValue) {
        int left = 0;
        int right = a.size()-1;
        while (left <= right) {
            int midpoint = (left + right) / 2;
            int result = ((Comparable) a.get(midpoint)).compareTo(searchValue);
            if (result == 0) {
                return midpoint;
            } else if (result < 0) {
                left = midpoint + 1;
            } else {
                right = midpoint - 1;
            }
        }
        return -1;

    }
    
    
    public final void computetotalprice(){
        price=price+p.sumworth();
        
    }
    public final int getprice(){
    return price;};
    public void clearmenu(){
        txtname.setText("");
        txtfashion.setText("");
        txtcomfort.setText("");
        txtwork.setText("");
        txtmatcosts.setText("");
        txtexclusive.setText("");
        txtprice.setText("");
        txtindex.setText("");
        txtnumber.setText("");
        lblexclusive.setText("");}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblname = new javax.swing.JLabel();
        lblfashion = new javax.swing.JLabel();
        lblcomfort = new javax.swing.JLabel();
        lblwork = new javax.swing.JLabel();
        lblmatcosts = new javax.swing.JLabel();
        lblexclusive = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtfashion = new javax.swing.JTextField();
        txtcomfort = new javax.swing.JTextField();
        txtwork = new javax.swing.JTextField();
        txtmatcosts = new javax.swing.JTextField();
        txtexclusive = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        lblprice = new javax.swing.JLabel();
        lblnumber = new javax.swing.JLabel();
        txtnumber = new javax.swing.JTextField();
        btnfirst = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        lblindex = new javax.swing.JLabel();
        txtindex = new javax.swing.JTextField();
        txtnummaintenances = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMInewdress = new javax.swing.JMenuItem();
        jMInewbag = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMIlining = new javax.swing.JMenuItem();
        jMIdecorations = new javax.swing.JMenuItem();
        jMIlock = new javax.swing.JMenuItem();
        jMInoiron = new javax.swing.JMenuItem();
        jMImaintenance = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMISell = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMIexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        lblname.setText("                               Model Name->");
        lblname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblfashion.setText("                            Fashion Level->");
        lblfashion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblcomfort.setText("                           Comfort Level->");
        lblcomfort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblwork.setText("                            Working Time->");
        lblwork.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblmatcosts.setText("                      Cost Of Materials->");
        lblmatcosts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtfashion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtcomfort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtwork.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtworkActionPerformed(evt);
            }
        });

        txtmatcosts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtexclusive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        lblprice.setText("                              Selling Price->");
        lblprice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblnumber.setText("       Total Number Of Products->");
        lblnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberActionPerformed(evt);
            }
        });

        btnfirst.setText("<|");
        btnfirst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });

        btnprevious.setText("<");
        btnprevious.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });

        btnnext.setText(">");
        btnnext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnlast.setText(">|");
        btnlast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        lblindex.setText("                          Current Index->");
        lblindex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtindex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtnummaintenances.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("     #  Of  Maintenance Cupons->");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu1.setText("New     ");

        jMInewdress.setText("New Dress");
        jMInewdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMInewdressActionPerformed(evt);
            }
        });
        jMenu1.add(jMInewdress);

        jMInewbag.setText("New Bag");
        jMInewbag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMInewbagActionPerformed(evt);
            }
        });
        jMenu1.add(jMInewbag);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu2.setText("Customise    ");

        jMIlining.setText("Add Lining");
        jMIlining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIliningActionPerformed(evt);
            }
        });
        jMenu2.add(jMIlining);

        jMIdecorations.setText("Add Decorations");
        jMIdecorations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIdecorationsActionPerformed(evt);
            }
        });
        jMenu2.add(jMIdecorations);

        jMIlock.setText("Add Safety Lock For Bag");
        jMIlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIlockActionPerformed(evt);
            }
        });
        jMenu2.add(jMIlock);

        jMInoiron.setText("Add Noniron Tissue For Dress");
        jMInoiron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMInoironActionPerformed(evt);
            }
        });
        jMenu2.add(jMInoiron);

        jMImaintenance.setText("Add Maintenance Coupons ");
        jMImaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMImaintenanceActionPerformed(evt);
            }
        });
        jMenu2.add(jMImaintenance);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu3.setText("Sell     ");

        jMISell.setText("Sell Current Item");
        jMISell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISellActionPerformed(evt);
            }
        });
        jMenu3.add(jMISell);

        jMenuBar1.add(jMenu3);

        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu4.setText("Exit");

        jMIexit.setText("Exit Program");
        jMIexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIexitActionPerformed(evt);
            }
        });
        jMenu4.add(jMIexit);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(btnprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblmatcosts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblwork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblcomfort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblfashion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(lblindex, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(lblnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblexclusive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtexclusive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtmatcosts, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtwork, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcomfort, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtfashion)
                            .addComponent(txtname)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                            .addComponent(btnlast, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtnumber, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtindex, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtnummaintenances, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtprice, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfashion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfashion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcomfort, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcomfort, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblwork, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtwork, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmatcosts, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmatcosts, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtexclusive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlast, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblprice, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtprice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnummaintenances, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblindex, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtindex, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lblexclusive)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMInoironActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMInoironActionPerformed
     stuff.get(index).addfeatures(); 
     txtmatcosts.setText(""+stuff.get(index).getMaterialcosts());
     txtexclusive.setText(""+stuff.get(index).getEasytoiron());
     price=200+2*stuff.get(index).sumworth();
     txtprice.setText(""+price);
    // jMInoiron.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jMInoironActionPerformed

    private void jMImaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMImaintenanceActionPerformed
        stuff.get(index).discountmaintenance();
        if (stuff.get(index) instanceof Dress)
        {txtexclusive.setText(""+stuff.get(index).getEasytoiron());}
        else{txtexclusive.setText(""+stuff.get(index).getSafetoclose());}
        price=200+stuff.get(index).sumworth();
        txtprice.setText(""+price);
        txtnummaintenances.setText(""+Product.getNumberofMaintenance());
       // jMImaintenance.setEnabled(false);

    }//GEN-LAST:event_jMImaintenanceActionPerformed

    private void jMIexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIexitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jMIexitActionPerformed

    private void jMInewdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMInewdressActionPerformed
      
      String m=JOptionPane.showInputDialog(this, "Enter dress model");
      
       Product temp =new Dress(m);
       int alreadyinlist= search(stuff,temp );
        if (alreadyinlist >=0)
            
           {JOptionPane.showMessageDialog(this,"Bag model is already in the list!");
           clearmenu();
           return; }
           else {
        int locinsert = findInsertPoint(stuff,temp);
        
        stuff.add(locinsert,temp);
        list.add(locinsert, temp.getName());//}     
    
     txtname.setText(temp.getName());     
     txtfashion.setText(""+temp.getFashion());
     txtcomfort.setText(""+temp.getComfort());
     txtwork.setText(""+temp.getWorktime());
     txtmatcosts.setText(""+temp.getMaterialcosts());
     lblexclusive.setText("Easiness To Iron");
     
     txtexclusive.setText(""+temp.getEasytoiron());
     price=200;
     txtprice.setText(""+price);
     index=locinsert;
     numprod++;
     txtnumber.setText(""+numprod);
     txtindex.setText(""+index);
     jMIlock.setEnabled(false);
    jMInoiron.setEnabled(true);
    // jMIlining.setEnabled(true);
    // jMIdecorations.setEnabled(true);
    // jMImaintenance.setEnabled(true);
    }//GEN-LAST:event_jMInewdressActionPerformed
    }// 
    private void jMInewbagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMInewbagActionPerformed
       String m=JOptionPane.showInputDialog(this, "Enter bag model");
       Product temp =new Bag(m);
      int alreadyinlist= search(stuff,temp );
        if (alreadyinlist >=0)
            
           {JOptionPane.showMessageDialog(this,"bag model is already in the list!");
           clearmenu();
           return; }
           else 
       { 
        int locinsert = findInsertPoint(stuff,temp);
        
        stuff.add(locinsert,temp);
        list.add(locinsert, temp.getName());//
     txtname.setText(temp.getName());     
     txtfashion.setText(""+temp.getFashion());
     txtcomfort.setText(""+temp.getComfort());
     txtwork.setText(""+temp.getWorktime());
     txtmatcosts.setText(""+temp.getMaterialcosts());
     lblexclusive.setText("safety of closure");
     txtexclusive.setText(""+temp.getSafetoclose());
     price=200;
     txtprice.setText(""+price);
     index=locinsert;
     numprod++;
     txtnumber.setText(""+numprod);
     txtindex.setText(""+index);}
     jMIlock.setEnabled(true);
    jMInoiron.setEnabled(false);
    }//GEN-LAST:event_jMInewbagActionPerformed
    
    private void jMIliningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIliningActionPerformed
      stuff.get(index).addlinen(); 
      txtcomfort.setText(""+stuff.get(index).getComfort());
      txtmatcosts.setText(""+stuff.get(index).getMaterialcosts());
     price=200+stuff.get(index).sumworth();
     txtprice.setText(""+price);
    
    }//GEN-LAST:event_jMIliningActionPerformed

    private void jMIdecorationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIdecorationsActionPerformed
      stuff.get(index).addflowers();
      txtfashion.setText(""+stuff.get(index).getFashion());
      txtmatcosts.setText(""+stuff.get(index).getMaterialcosts());
      txtwork.setText(""+stuff.get(index).getWorktime());
     
     price=200+stuff.get(index).sumworth();
     txtprice.setText(""+price);
   
    }//GEN-LAST:event_jMIdecorationsActionPerformed

    private void txtworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtworkActionPerformed

    private void jMIlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIlockActionPerformed
      stuff.get(index).addfeatures(); 
     txtmatcosts.setText(""+stuff.get(index).getMaterialcosts());
     txtexclusive.setText(""+stuff.get(index).getSafetoclose());
    price=200+stuff.get(index).sumworth();
     
     txtprice.setText(""+price); 
    }//GEN-LAST:event_jMIlockActionPerformed

    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
       clearmenu();
        index=1;
       
        txtname.setText(stuff.get(index).getName());     
     txtfashion.setText(""+stuff.get(index).getFashion());
     txtcomfort.setText(""+stuff.get(index).getComfort());
     txtwork.setText(""+stuff.get(index).getWorktime());
     txtmatcosts.setText(""+stuff.get(index).getMaterialcosts());
     if (stuff.get(index) instanceof Bag){
     lblexclusive.setText("safety of closure");
     jMIlock.setEnabled(true);
     jMInoiron.setEnabled(false);
     }
     else{lblexclusive.setText("easiness to iron");
     jMIlock.setEnabled(false);
     jMInoiron.setEnabled(true);
     }
     txtexclusive.setText(""+stuff.get(index).getworth());
     //txtexclusive.setText(""+stuff.get(index).getworth());
    price=200+stuff.get(index).sumworth();
    txtprice.setText(""+price);
    txtnumber.setText(""+numprod);
     txtindex.setText(""+index);
     txtnummaintenances.setText(""+Product.getNumberofMaintenance());
    }//GEN-LAST:event_btnfirstActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
       clearmenu();
        index=numprod;
       
        txtname.setText(stuff.get(index).getName());     
     txtfashion.setText(""+stuff.get(index).getFashion());
     txtcomfort.setText(""+stuff.get(index).getComfort());
     txtwork.setText(""+stuff.get(index).getWorktime());
     txtmatcosts.setText(""+stuff.get(index).getMaterialcosts());
    if (stuff.get(index) instanceof Bag){
     lblexclusive.setText("safety of closure");
     jMIlock.setEnabled(true);
     jMInoiron.setEnabled(false);
    }
     else{lblexclusive.setText("easiness to iron");
    jMIlock.setEnabled(false);
     jMInoiron.setEnabled(true);
    }
      txtexclusive.setText(""+stuff.get(index).getworth());
    // txtexclusive.setText(""+p.getSafetoclose());
    price=200+stuff.get(index).sumworth();
    txtprice.setText(""+price);
    txtnumber.setText(""+numprod);
     txtindex.setText(""+index);
     txtnummaintenances.setText(""+Product.getNumberofMaintenance());
    }//GEN-LAST:event_btnlastActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
     if (index==numprod){return;}
     if (index<numprod)index++;  
     
        txtname.setText(stuff.get(index).getName());     
     txtfashion.setText(""+stuff.get(index).getFashion());
     txtcomfort.setText(""+stuff.get(index).getComfort());
     txtwork.setText(""+stuff.get(index).getWorktime());
     txtmatcosts.setText(""+stuff.get(index).getMaterialcosts());
     if (stuff.get(index) instanceof Bag){
     lblexclusive.setText("safety of closure");
     jMIlock.setEnabled(true);
     jMInoiron.setEnabled(false);
     }
     else{lblexclusive.setText("easiness to iron");
     jMIlock.setEnabled(false);
     jMInoiron.setEnabled(true);
     }
      txtexclusive.setText(""+stuff.get(index).getworth());
   price=200+stuff.get(index).sumworth();
    txtprice.setText(""+price);
    txtnumber.setText(""+numprod);
     txtindex.setText(""+index);
     txtnummaintenances.setText(""+Product.getNumberofMaintenance());
     
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
      if (index==1){return;}
     if (index>1)index--;  
     
        txtname.setText(stuff.get(index).getName());     
     txtfashion.setText(""+stuff.get(index).getFashion());
     txtcomfort.setText(""+stuff.get(index).getComfort());
     txtwork.setText(""+stuff.get(index).getWorktime());
     txtmatcosts.setText(""+stuff.get(index).getMaterialcosts());
    if (stuff.get(index) instanceof Bag){
     lblexclusive.setText("safety of closure");
    jMIlock.setEnabled(true);
     jMInoiron.setEnabled(false);
    }
     else{lblexclusive.setText("easiness to iron");
    jMIlock.setEnabled(false);
     jMInoiron.setEnabled(true);
    }
      txtexclusive.setText(""+stuff.get(index).getworth());
    price=200+stuff.get(index).sumworth();
    txtprice.setText(""+price);
    txtnumber.setText(""+numprod);
     txtindex.setText(""+index); 
     txtnummaintenances.setText(""+Product.getNumberofMaintenance());
    }//GEN-LAST:event_btnpreviousActionPerformed

    private void jMISellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISellActionPerformed
     if (index==stuff.size()-1){
        stuff.remove(stuff.get(index));
    list.removeElementAt(index);
    numprod--;
    index--;
    clearmenu();
       txtname.setText(stuff.get(index).getName());     
     txtfashion.setText(""+stuff.get(index).getFashion());
     txtcomfort.setText(""+stuff.get(index).getComfort());
     txtwork.setText(""+stuff.get(index).getWorktime());
     txtmatcosts.setText(""+stuff.get(index).getMaterialcosts());
     if (stuff.get(index) instanceof Bag){
     lblexclusive.setText("safety of closure");
     jMIlock.setEnabled(true);
     jMInoiron.setEnabled(false);
     }
     else{lblexclusive.setText("easiness to iron");
     jMIlock.setEnabled(false);
     jMInoiron.setEnabled(true);
     }
      txtexclusive.setText(""+stuff.get(index).getworth());
    price=200+stuff.get(index).sumworth();
    txtprice.setText(""+price);
    txtnumber.setText(""+numprod);
     txtindex.setText(""+index);}
     else {
         stuff.remove(stuff.get(index));
    list.removeElementAt(index);
    numprod--;
    clearmenu();
       txtname.setText(stuff.get(index).getName());     
     txtfashion.setText(""+stuff.get(index).getFashion());
     txtcomfort.setText(""+stuff.get(index).getComfort());
     txtwork.setText(""+stuff.get(index).getWorktime());
     txtmatcosts.setText(""+stuff.get(index).getMaterialcosts());
     if (stuff.get(index) instanceof Bag){
     lblexclusive.setText("safety of closure");
     jMIlock.setEnabled(true);
     jMInoiron.setEnabled(false);
     }
     else{lblexclusive.setText("easiness to iron");
     jMIlock.setEnabled(false);
     jMInoiron.setEnabled(true);
     }
      txtexclusive.setText(""+stuff.get(index).getworth());
    price=200+stuff.get(index).sumworth();
    txtprice.setText(""+price);
    txtnumber.setText(""+numprod);
     txtindex.setText(""+index);}
     
         
     
    
    }//GEN-LAST:event_jMISellActionPerformed

    private void txtnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumberActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taylor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taylor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taylor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taylor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taylor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMISell;
    private javax.swing.JMenuItem jMIdecorations;
    private javax.swing.JMenuItem jMIexit;
    private javax.swing.JMenuItem jMIlining;
    private javax.swing.JMenuItem jMIlock;
    private javax.swing.JMenuItem jMImaintenance;
    private javax.swing.JMenuItem jMInewbag;
    private javax.swing.JMenuItem jMInewdress;
    private javax.swing.JMenuItem jMInoiron;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblcomfort;
    private javax.swing.JLabel lblexclusive;
    private javax.swing.JLabel lblfashion;
    private javax.swing.JLabel lblindex;
    private javax.swing.JLabel lblmatcosts;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnumber;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblwork;
    private javax.swing.JTextField txtcomfort;
    private javax.swing.JTextField txtexclusive;
    private javax.swing.JTextField txtfashion;
    private javax.swing.JTextField txtindex;
    private javax.swing.JTextField txtmatcosts;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtnummaintenances;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtwork;
    // End of variables declaration//GEN-END:variables
}
